# -*- coding: utf-8 -*-
"""NepaliParser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yyjRJyO0Mb3PAUy9qaTkZ2aMJItVuma7
"""

import re
import json

POS_DICT = {

    # Pronouns
    "म": ("PRON", 0.99), "हामी": ("PRON", 0.99),
    "तिमी": ("PRON", 0.98), "तपाईं": ("PRON", 0.98),
    "उ": ("PRON", 0.97), "उनी": ("PRON", 0.97),

    # Determiners
    "यो": ("DET", 0.96), "त्यो": ("DET", 0.96),

    # Proper nouns
    "राम": ("PROPN", 0.99), "सीता": ("PROPN", 0.99),
    "श्याम": ("PROPN", 0.99), "गीता": ("PROPN", 0.99),
    "नेपाल": ("PROPN", 0.99), "भारत": ("PROPN", 0.99),
    "काठमाडौं": ("PROPN", 0.99), "पोखरा": ("PROPN", 0.99),

    # Nouns
    "किताब": ("NOUN", 0.98), "घर": ("NOUN", 0.98),
    "विद्यालय": ("NOUN", 0.98), "स्कुल": ("NOUN", 0.98),
    "पानी": ("NOUN", 0.97), "खाना": ("NOUN", 0.97),
    "काम": ("NOUN", 0.97), "देश": ("NOUN", 0.97),
    "शहर": ("NOUN", 0.97), "गाउँ": ("NOUN", 0.97),

    # Adjectives
    "राम्रो": ("ADJ", 0.98), "ठूलो": ("ADJ", 0.98),
    "सानो": ("ADJ", 0.97), "नयाँ": ("ADJ", 0.97),
    "पुरानो": ("ADJ", 0.97), "सुन्दर": ("ADJ", 0.97),

    # Verbs
    "गर्छ": ("VERB", 0.98), "गरे": ("VERB", 0.98),
    "गयो": ("VERB", 0.98), "पढ्छ": ("VERB", 0.98),
    "पढ्यो": ("VERB", 0.98), "जान्छ": ("VERB", 0.97),
    "आयो": ("VERB", 0.97), "आउँछ": ("VERB", 0.97),
    "खान्छ": ("VERB", 0.97), "खायो": ("VERB", 0.97),

    # Auxiliary
    "छ": ("AUX", 0.99), "छन्": ("AUX", 0.99),
    "छु": ("AUX", 0.99), "थियो": ("AUX", 0.98),

    # Postpositions
    "मा": ("ADP", 0.99), "ले": ("ADP", 0.99),
    "लाई": ("ADP", 0.99), "बाट": ("ADP", 0.99),
    "सँग": ("ADP", 0.98),

    # Conjunction
    "र": ("CONJ", 0.99), "तर": ("CONJ", 0.99),

    # Adverbs
    "छिटो": ("ADV", 0.97), "ढिलो": ("ADV", 0.97),
    "धेरै": ("ADV", 0.97), "अहिले": ("ADV", 0.97),

    # Numbers
    "एक": ("NUM", 0.98), "दुई": ("NUM", 0.98),
    "तीन": ("NUM", 0.98),
}


# Tokenizer

def tokenize(text):
    text = re.sub(r'([।.,!?])', r' \1 ', text)
    return text.split()


# POS Tagging

def pos_tag(tokens):
    result = []
    for tok in tokens:
        if tok in "।.,!?":
            result.append({"token": tok, "tag": "PUNCT", "score": 1.0})
        elif tok in POS_DICT:
            tag, score = POS_DICT[tok]
            result.append({"token": tok, "tag": tag, "score": score})
        else:
            # Heuristic fallback
            if tok.endswith(("छ", "छन्", "छु")):
                tag = "AUX"
            elif tok.endswith(("दै", "दा", "यो", "ए")):
                tag = "VERB"
            elif tok.endswith(("ो", "ी", "ा")):
                tag = "ADJ"
            else:
                tag = "NOUN"

            result.append({"token": tok, "tag": tag, "score": 0.6})
    return result


# Dependency Parsing

def dependency_parse(tagged):
    deps = []
    root_idx = None

    # Find root (first verb)
    for i, t in enumerate(tagged):
        if t["tag"] == "VERB":
            root_idx = i
            break

    if root_idx is None:
        root_idx = 0

    root = tagged[root_idx]["token"]

    for i, t in enumerate(tagged):
        if i == root_idx:
            deps.append({"token": t["token"], "dep": "ROOT"})
        elif t["tag"] in ("PRON", "PROPN") and i < root_idx:
            deps.append({"token": t["token"], "dep": "nsubj"})
        elif t["tag"] == "NOUN":
            deps.append({"token": t["token"], "dep": "obj"})
        elif t["tag"] == "ADJ":
            deps.append({"token": t["token"], "dep": "amod"})
        elif t["tag"] == "ADV":
            deps.append({"token": t["token"], "dep": "advmod"})
        elif t["tag"] == "ADP":
            deps.append({"token": t["token"], "dep": "case"})
        elif t["tag"] == "AUX":
            deps.append({"token": t["token"], "dep": "aux"})
        else:
            deps.append({"token": t["token"], "dep": "dep"})

    return deps


# Sentence Splitter

def split_sentences(text):
    return [s.strip() for s in re.split(r'[।!?]', text) if s.strip()]


# Main Parser

def parse_text(text):
    sentences = split_sentences(text)
    results = []

    for sent in sentences:
        tokens = tokenize(sent)
        tagged = pos_tag(tokens)
        deps = dependency_parse(tagged)

        results.append({
            "sentence": sent,
            "tokens": tokens,
            "pos_tags": tagged,
            "dependencies": deps
        })

    return results

# TEST INPUT

text = "राम किताब पढ्छ। नेपाल राम्रो देश हो"

result = parse_text(text)

while True:
    text = input("\nEnter Nepali sentence (or type 'exit'): ")

    if text.lower() == "exit":
        print("Exiting...")
        break

    result = parse_text(text)

    print("\n--- RESULT ---")
    for r in result:
        print("\nSentence:", r["sentence"])
        print("Tokens:", r["tokens"])
        print("POS Tags:")
        for t in r["pos_tags"]:
            print(f"  {t['token']} -> {t['tag']} ({t['score']})")

        print("Dependencies:")
        for d in r["dependencies"]:
            print(f"  {d['token']} -> {d['dep']}")

